import { useState, useEffect } from 'react'
import { collection, query, where, getDocs, deleteDoc, doc } from 'firebase/firestore'
import { db } from '../firebase/config'
import { DAYS } from '../data/exercises'
import { Trash2, ChevronDown, ChevronUp } from 'lucide-react'

export default function History({ user }) {
  const [workouts, setWorkouts] = useState([])
    const [loading, setLoading] = useState(true)
      const [expanded, setExpanded] = useState({})

        useEffect(() => { load() }, [user.uid])

          const load = async () => {
              setLoading(true)
                  try {
                        const q = query(collection(db,'workouts'), where('uid','==',user.uid))
                              const snap = await getDocs(q)
                                    const data = snap.docs.map(d=>({id:d.id,...d.data()}))
                                          data.sort((a,b) => (b.date?.toDate()||0) - (a.date?.toDate()||0))
                                                setWorkouts(data)
                                                    } catch(e) { console.error('history error',e) }
                                                        setLoading(false)
                                                          }

                                                            const del = async (id) => {
                                                                if (!window.confirm('Usunac ten trening?')) return
                                                                    try { await deleteDoc(doc(db,'workouts',id)); setWorkouts(w=>w.filter(x=>x.id!==id)) }
                                                                        catch(e) { console.error(e) }
                                                                          }

                                                                            return (
                                                                                <div>
                                                                                      <h1 style={{fontFamily:'var(--font-display)',fontSize:32,letterSpacing:2,marginBottom:4}}>HISTORIA</h1>
                                                                                            <p style={{color:'var(--text3)',fontSize:13,marginBottom:20}}>Wszystkie Twoje treningi</p>
                                                                                                  {loading ? <div style={{color:'var(--text3)'}}>Ladowanie...</div> :
                                                                                                        workouts.length===0 ? <div className='card' style={{textAlign:'center',padding:'30px',color:'var(--text3)'}}>Brak treningow</div> :
                                                                                                              <div style={{display:'flex',flexDirection:'column',gap:10}}>
                                                                                                                      {workouts.map(w=>(
                                                                                                                                <div key={w.id} className='card' style={{padding:0,overflow:'hidden'}}>
                                                                                                                                            <div style={{display:'flex',alignItems:'center',gap:12,padding:'14px 16px',cursor:'pointer'}} onClick={()=>setExpanded(e=>({...e,[w.id]:!e[w.id]}))}>              <div style={{width:40,height:40,borderRadius:8,background:(DAYS[w.day]?.color||'#888')+'22',display:'flex',alignItems:'center',justifyContent:'center',fontFamily:'var(--font-display)',fontSize:18,color:DAYS[w.day]?.color||'#888',flexShrink:0}}>{w.day}</div>
                                                                                                                                                          <div style={{flex:1}}>
                                                                                                                                                                          <div style={{fontSize:14,fontWeight:600}}>{DAYS[w.day]?.label||w.day}</div>
                                                                                                                                                                                          <div style={{fontSize:12,color:'var(--text3)'}}>{w.date?.toDate().toLocaleDateString('pl-PL',{day:'numeric',month:'long',year:'numeric'})}</div>
                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                      <div style={{fontSize:12,color:'var(--text2)',marginRight:8}}>{w.exercises?.length||0} cw.</div>
                                                                                                                                                                                                                                    <button onClick={e=>{e.stopPropagation();del(w.id)}} style={{background:'none',color:'var(--danger)',padding:4}}><Trash2 size={15}/></button>
                                                                                                                                                                                                                                                  {expanded[w.id]?<ChevronUp size={16} color='var(--text3)'/>:<ChevronDown size={16} color='var(--text3)'/>}
                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                          {expanded[w.id]&&(
                                                                                                                                                                                                                                                                                        <div style={{padding:'12px 16px 16px',borderTop:'1px solid var(--border)',background:'var(--bg3)'}}>
                                                                                                                                                                                                                                                                                                        {(w.exercises||[]).map((ex,i)=>(
                                                                                                                                                                                                                                                                                                                          <div key={i} style={{marginBottom:10}}>
                                                                                                                                                                                                                                                                                                                                              <div style={{fontSize:13,fontWeight:600,marginBottom:4}}>{ex.name}</div>
                                                                                                                                                                                                                                                                                                                                                                  <div style={{display:'flex',gap:8,flexWrap:'wrap'}}>
                                                                                                                                                                                                                                                                                                                                                                                        {(ex.sets||[]).map((s,j)=>(
                                                                                                                                                                                                                                                                                                                                                                                                                <span key={j} style={{fontSize:12,padding:'3px 10px',background:'var(--bg2)',borderRadius:10,color:'var(--text2)',border:'1px solid var(--border)'}}>
                                                                                                                                                                                                                                                                                                                                                                                                                                          {s.weight?s.weight+'kg ':''}{s.reps}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }