import { useState, useEffect } from 'react'
import { collection, query, where, getDocs } from 'firebase/firestore'
import { db } from '../firebase/config'
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts'

export default function Progress({ user }) {
  const [workouts, setWorkouts] = useState([])
    const [selected, setSelected] = useState('')
      const [loading, setLoading] = useState(true)
        const [exercises, setExercises] = useState([])

          useEffect(() => { load() }, [user.uid])

            const load = async () => {
                setLoading(true)
                    try {
                          const q = query(collection(db,'workouts'), where('uid','==',user.uid))
                                const snap = await getDocs(q)
                                      const data = snap.docs.map(d=>({id:d.id,...d.data()}))
                                            data.sort((a,b)=>(a.date?.toDate()||0)-(b.date?.toDate()||0))
                                                  setWorkouts(data)
                                                        const exSet = new Set()
                                                              data.forEach(w=>w.exercises?.forEach(e=>exSet.add(e.name)))
                                                                    const allEx = [...exSet].sort()
                                                                          setExercises(allEx)
                                                                                if (allEx.length>0) setSelected(allEx[0])
                                                                                    } catch(e) { console.error('progress error',e) }
                                                                                        setLoading(false)
                                                                                          }

                                                                                            const chartData = workouts
                                                                                                .filter(w=>w.exercises?.some(e=>e.name===selected))
                                                                                                    .map(w=>{
                                                                                                          const ex = w.exercises?.find(e=>e.name===selected)
                                                                                                                const maxW = Math.max(...(ex?.sets||[]).map(s=>parseFloat(s.weight)||0))
                                                                                                                      return { date:w.date?.toDate().toLocaleDateString('pl-PL',{day:'numeric',month:'short'}), max:maxW||null }
                                                                                                                          })
                                                                                                                              .filter(d=>d.max)

                                                                                                                                const Tip = ({active,payload,label}) => active&&payload?.length?(
                                                                                                                                    <div style={{background:'var(--bg2)',border:'1px solid var(--border)',borderRadius:8,padding:'10px 14px',fontSize:13}}>
                                                                                                                                          <div style={{color:'var(--text2)',marginBottom:4}}>{label}</div>
                                                                                                                                                <div style={{color:'var(--accent)',fontWeight:600}}>{payload[0].value} kg</div>
                                                                                                                                                    </div>
                                                                                                                                                      ):null

                                                                                                                                                        return (
                                                                                                                                                            <div>
                                                                                                                                                                  <h1 style={{fontFamily:'var(--font-display)',fontSize:32,letterSpacing:2,marginBottom:4}}>POSTEP</h1>
                                                                                                                                                                        <p style={{color:'var(--text3)',fontSize:13,marginBottom:20}}>Sledzenie maksymalnych ciezarow</p>
                                                                                                                                                                              {loading?<div style={{color:'var(--text3)'}}>Ladowanie...</div>:
                                                                                                                                                                                    exercises.length===0?<div className='card' style={{textAlign:'center',padding:'30px',color:'var(--text3)'}}>Najpierw dodaj treningi</div>:(
                                                                                                                                                                                            <>
                                                                                                                                                                                                      <div className='card' style={{marginBottom:16}}>
                                                                                                                                                                                                                  <label style={{fontSize:12,color:'var(--text2)',marginBottom:8,display:'block'}}>Wybierz cwiczenie</label>
                                                                                                                                                                                                                              <select value={selected} onChange={e=>setSelected(e.target.value)} style={{width:'100%',padding:'10px 14px',fontSize:14}}>
                                                                                                                                                                                                                                            {exercises.map(ex=><option key={ex} value={ex}>{ex}</option>)}
                                                                                                                                                                                                                                                        </select>
                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                            {chartData.length<2?<div className='card' style={{textAlign:'center',padding:'20px',color:'var(--text3)',fontSize:13}}>Potrzebujesz min. 2 treningi z tym cwiczeniem</div>:(
                                                                                                                                                                                                                                                                                        <div className='card'>
                                                                                                                                                                                                                                                                                                      <div style={{fontSize:14,fontWeight:600,marginBottom:16}}>Max ciezar (kg) - {selected}</div>
                                                                                                                                                                                                                                                                                                                    <ResponsiveContainer width='100%' height={240}>
                                                                                                                                                                                                                                                                                                                                    <LineChart data={chartData}>
                                                                                                                                                                                                                                                                                                                                                      <CartesianGrid strokeDasharray='3 3' stroke='#1e2d45'/>
                                                                                                                                                                                                                                                                                                                                                                        <XAxis dataKey='date' tick={{fontSize:11,fill:'#475569'}}/>
                                                                                                                                                                                                                                                                                                                                                                                          <YAxis tick={{fontSize:11,fill:'#475569'}}/>
                                                                                                                                                                                                                                                                                                                                                                                                            <Tooltip content={<Tip/>}/>
                                                                                                                                                                                                                                                                                                                                                                                                                              <Line type='monotone' dataKey='max' stroke='var(--accent)' strokeWidth={2} dot={{fill:'var(--accent)',r:4}} activeDot={{r:6}}/>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </LineChart>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ResponsiveContainer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }